site_name: Protocol Buffers Hardware Accelerator - ICE-RLab Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Contributing Guidelines: contributing.md
theme: readthedocs
markdown_extensions:
  - admonition
plugins:
  - gh-admonitions
