site_name: Protobuf Acc Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Contributing to the Docs: contributing.md
theme: readthedocs
markdown_extensions:
  - admonition
plugins:
  - gh-admonitions
